#!/bin/bash
echo "Crawling over to the tmp folder my lord.."
echo ""
startingPath="$PWD"
cd /tmp
sudo apt install apt-transport-https ca-certificates curl software-properties-common -y
sudo apt install tilix -y
sudo apt install jq -y
sudo apt install zip -y
sudo apt install build-essential -y
echo "installing podman"
echo ""
sudo apt-get install -qq -y software-properties-common uidmap
./update
sudo apt-get -qq -y install podman
echo "installing things for yubikeys"
sudo apt-get -qq -y install libpam-u2f
echo "Moving back to where we was before my liege!"
cd "$startingPath"
