#!/bin/bash
echo "Crawling over to the tmp folder my lord.."
echo ""
startingPath="$PWD"
cd /tmp
sudo apt install apt-transport-https ca-certificates curl software-properties-common -y
sudo apt install tilix -y
sudo apt install jq -y
echo "installing podman"
echo ""
./update
sudo apt-get install -qq -y software-properties-common uidmap
sudo add-apt-repository -y ppa:projectatomic/ppa
./update
echo "Moving back to where we was before my liege!"
cd "$startingPath"
