#!/bin/bash
./update
echo "installing zsh"
sudo apt install zsh -y
echo "making zsh default shell"
chsh -s $(which zsh)
echo "installing oh-my-zshell"
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
echo "installation complete, it will work after a new login"
